# Generated by Django 3.1.3 on 2022-01-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageviewcount',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listedstockinfo',
            name='MarketType',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='listedstockinfo',
            name='MarketTypeDetail',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
