# Generated by Django 3.1.3 on 2022-02-06 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_auto_20220128_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockcalcdata',
            fields=[
                ('trade_date', models.DateField()),
                ('StockCode', models.CharField(max_length=20)),
                ('StockName', models.CharField(blank=True, max_length=100, null=True)),
                ('MarketType', models.CharField(blank=True, max_length=15, null=True)),
                ('ClosePrice', models.FloatField()),
                ('TopBottomRate', models.FloatField()),
                ('Ave20Volume', models.FloatField()),
                ('Ave20VolWeight', models.FloatField()),
                ('Ave12Price', models.FloatField()),
                ('Ave26Price', models.FloatField()),
                ('MaxHighPrice', models.FloatField()),
                ('MinLowPrice', models.FloatField()),
                ('SlowStoD', models.FloatField()),
                ('STDevRate', models.FloatField()),
                ('BolingerBandCenterBarr', models.FloatField()),
                ('BolingerBandUpBarr', models.FloatField()),
                ('BolingerBandDownBarr', models.FloatField()),
                ('MACD', models.FloatField()),
                ('Ave9MACDSignal', models.FloatField()),
                ('MACDOsil', models.FloatField()),
                ('MACDOsilRate', models.FloatField()),
                ('RSI', models.FloatField()),
                ('RSI_Flag', models.FloatField()),
                ('OBV', models.FloatField()),
                ('OBVSignal', models.FloatField()),
                ('OBV_Flag', models.FloatField()),
                ('VR', models.FloatField()),
                ('VR_Flag', models.FloatField()),
                ('StockCalcData_ID', models.CharField(default='', max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='stockpriceinfo',
            fields=[
                ('trade_date', models.CharField(max_length=20)),
                ('MarketType', models.CharField(max_length=15)),
                ('StockCode', models.CharField(max_length=20)),
                ('StockName', models.CharField(blank=True, max_length=100, null=True)),
                ('OpenPrice', models.FloatField()),
                ('HighPrice', models.FloatField()),
                ('LowPrice', models.FloatField()),
                ('ClosePrice', models.FloatField()),
                ('TradeVolume', models.FloatField()),
                ('StockPriceInfo_ID', models.CharField(default='', max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='stockbarcodedata',
            name='StockCalcData',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pybo.stockcalcdata'),
        ),
        migrations.AddField(
            model_name='stockbarcodedata',
            name='StockPriceInfo',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pybo.stockpriceinfo'),
        ),
    ]
