# Generated by Django 3.1.3 on 2022-02-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_auto_20220206_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedstockinfo',
            name='FinalPriceT',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='FinalPriceT1',
            field=models.FloatField(default=0),
        ),
    ]
