# Generated by Django 3.1.3 on 2022-01-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_question_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='notice',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
