# Generated by Django 3.1.3 on 2022-02-12 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_auto_20220211_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntBuySellInfo',
            fields=[
                ('StockCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('StockName', models.CharField(blank=True, max_length=100, null=True)),
                ('TradeVolume_Sell', models.FloatField(default=0)),
                ('TradeVolume_Buy', models.FloatField(default=0)),
                ('TradeVolume_NetBuy', models.FloatField(default=0)),
                ('TradeAmount_Sell', models.FloatField(default=0)),
                ('TradeAmount_Buy', models.FloatField(default=0)),
                ('TradeAmount_NetBuy', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ForeignBuySellInfo',
            fields=[
                ('StockCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('StockName', models.CharField(blank=True, max_length=100, null=True)),
                ('TradeVolume_Sell', models.FloatField(default=0)),
                ('TradeVolume_Buy', models.FloatField(default=0)),
                ('TradeVolume_NetBuy', models.FloatField(default=0)),
                ('TradeAmount_Sell', models.FloatField(default=0)),
                ('TradeAmount_Buy', models.FloatField(default=0)),
                ('TradeAmount_NetBuy', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteBuySellInfo',
            fields=[
                ('StockCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('StockName', models.CharField(blank=True, max_length=100, null=True)),
                ('TradeVolume_Sell', models.FloatField(default=0)),
                ('TradeVolume_Buy', models.FloatField(default=0)),
                ('TradeVolume_NetBuy', models.FloatField(default=0)),
                ('TradeAmount_Sell', models.FloatField(default=0)),
                ('TradeAmount_Buy', models.FloatField(default=0)),
                ('TradeAmount_NetBuy', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='stockbarcodedata',
            name='AntBuySellInfo',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pybo.antbuysellinfo'),
        ),
        migrations.AddField(
            model_name='stockbarcodedata',
            name='ForeignBuySellInfo',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pybo.foreignbuysellinfo'),
        ),
        migrations.AddField(
            model_name='stockbarcodedata',
            name='InstituteBuySellInfo',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pybo.institutebuysellinfo'),
        ),
    ]
