# Generated by Django 3.1.3 on 2022-01-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_question_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('create_date', models.DateTimeField()),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
