# Generated by Django 3.1.3 on 2022-02-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_auto_20220212_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedstockinfo',
            name='BPS',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='DivAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='DivRate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='EPS',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='Forward_EPS',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='Forward_PER',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='IndustryType',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='PBR',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='PER',
            field=models.FloatField(default=0),
        ),
    ]
