# Generated by Django 3.1.3 on 2022-01-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_pageviewcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageviewcount',
            name='create_date',
            field=models.DateField(),
        ),
    ]
