# Generated by Django 3.1.3 on 2022-02-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20220219_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedstockinfo',
            name='FinalPriceT30',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='FinalPriceT7',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='FinalPriceT90',
            field=models.FloatField(default=0),
        ),
    ]
