# Generated by Django 3.1.3 on 2022-04-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20220219_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='listedstockinfo',
            name='ForeignStockNo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='ForeignStockRate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='ShortSellAmont',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='ShortSellNum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='ShortSellRate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='TodayShortTradeAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='TodayShortTradeNum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='TodayShortTradeRate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='TodayTotalTradeAmount',
            field=models.FloatField(default=0),
        ),
    ]
