# Generated by Django 3.1.3 on 2023-05-17 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20220219_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='twinstockbarcodeperfreturn',
            fields=[
                ('trade_date', models.DateField()),
                ('StockCode', models.CharField(max_length=20)),
                ('StockName', models.CharField(blank=True, max_length=100, null=True)),
                ('MarketType', models.CharField(max_length=15)),
                ('ClosePrice', models.FloatField()),
                ('BarFinalCode', models.CharField(blank=True, max_length=20, null=True)),
                ('BarFinalCodeDtl', models.CharField(blank=True, max_length=20, null=True)),
                ('Day1PL', models.FloatField()),
                ('Day1Return', models.FloatField()),
                ('ClosePriceAft1', models.FloatField()),
                ('Day7PL', models.FloatField()),
                ('Day7Return', models.FloatField()),
                ('ClosePriceAft7', models.FloatField()),
                ('Day30PL', models.FloatField()),
                ('Day30Return', models.FloatField()),
                ('ClosePriceAft30', models.FloatField()),
                ('Day90PL', models.FloatField()),
                ('Day90Return', models.FloatField()),
                ('ClosePriceAft90', models.FloatField()),
                ('Day180PL', models.FloatField()),
                ('Day180Return', models.FloatField()),
                ('ClosePriceAft180', models.FloatField()),
                ('Day360PL', models.FloatField()),
                ('Day360Return', models.FloatField()),
                ('ClosePriceAft360', models.FloatField()),
                ('TodayPL', models.FloatField(blank=True, null=True)),
                ('TodayReturn', models.FloatField(blank=True, null=True)),
                ('StockBarcode_ID', models.CharField(default='', max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='ForeignStockNo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='ForeignStockRate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='ShortSellAmont',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='ShortSellNum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='ShortSellRate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='TodayShortTradeAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='TodayShortTradeNum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='TodayShortTradeRate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listedstockinfo',
            name='TodayTotalTradeAmount',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='twinstockbarcodedata',
            fields=[
                ('trade_date', models.DateField()),
                ('StockCode', models.CharField(max_length=20)),
                ('StockName', models.CharField(blank=True, max_length=100, null=True)),
                ('MarketType', models.CharField(max_length=15)),
                ('ClosePrice', models.FloatField()),
                ('BarType', models.CharField(blank=True, max_length=20, null=True)),
                ('BarLengthType', models.CharField(blank=True, max_length=20, null=True)),
                ('HammerType', models.CharField(blank=True, max_length=20, null=True)),
                ('StochasticFlag', models.CharField(blank=True, max_length=20, null=True)),
                ('BolingerBandPos', models.CharField(blank=True, max_length=20, null=True)),
                ('VolumeFlag', models.CharField(blank=True, max_length=20, null=True)),
                ('MACDFlag', models.CharField(blank=True, max_length=20, null=True)),
                ('StrategyCond', models.CharField(blank=True, max_length=20, null=True)),
                ('STDevStochasticFlag', models.CharField(blank=True, max_length=20, null=True)),
                ('BarFinalCode', models.CharField(default='', max_length=20)),
                ('BarFinalCodeDtl', models.CharField(blank=True, max_length=20, null=True)),
                ('StochasticCrossFlag', models.CharField(blank=True, max_length=20, null=True)),
                ('StockBarcode_ID', models.CharField(default='', max_length=150, primary_key=True, serialize=False)),
                ('AntBuySellInfo', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pybo.antbuysellinfo')),
                ('ForeignBuySellInfo', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pybo.foreignbuysellinfo')),
                ('InstituteBuySellInfo', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pybo.institutebuysellinfo')),
                ('ListedStockInfo', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pybo.listedstockinfo')),
                ('StockBarcodePerfTotal', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pybo.stockbarcodeperftotal')),
                ('StockCalcData', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pybo.stockcalcdata')),
                ('StockPriceInfo', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pybo.stockpriceinfo')),
                ('TwinStockBarcodePerfReturn', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pybo.twinstockbarcodeperfreturn')),
            ],
        ),
    ]
