# Generated by Django 3.1.3 on 2021-12-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_stockbarcodedata_stockbarcodeperfreturn_stockbarcodeperftotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbarcodedata',
            name='trade_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stockbarcodeperfreturn',
            name='TradeDate',
            field=models.DateField(),
        ),
    ]
