# Generated by Django 3.1.3 on 2021-12-25 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_auto_20211225_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbarcodedata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stockbarcodeperfreturn',
            name='BarFinalCode',
        ),
        migrations.RemoveField(
            model_name='stockbarcodeperfreturn',
            name='BarFinalCodeDtl',
        ),
        migrations.RemoveField(
            model_name='stockbarcodeperfreturn',
            name='ClosePrice',
        ),
        migrations.RemoveField(
            model_name='stockbarcodeperfreturn',
            name='MarketType',
        ),
        migrations.RemoveField(
            model_name='stockbarcodeperfreturn',
            name='StockCode',
        ),
        migrations.RemoveField(
            model_name='stockbarcodeperfreturn',
            name='StockName',
        ),
        migrations.RemoveField(
            model_name='stockbarcodeperfreturn',
            name='TradeDate',
        ),
        migrations.RemoveField(
            model_name='stockbarcodeperftotal',
            name='BarFinalCodeDtl',
        ),
        migrations.RemoveField(
            model_name='stockbarcodeperftotal',
            name='id',
        ),
        migrations.AddField(
            model_name='stockbarcodedata',
            name='StockBarcode_ID',
            field=models.CharField(default='AAA', max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='stockbarcodeperfreturn',
            name='StockBarcodeData',
            field=models.ForeignKey(default='AAA', on_delete=django.db.models.deletion.CASCADE, to='pybo.stockbarcodedata'),
        ),
        migrations.AddField(
            model_name='stockbarcodeperftotal',
            name='StockBarcodePerfTotal_ID',
            field=models.CharField(default='AAA', max_length=150, primary_key=True, serialize=False),
        ),
    ]
